// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ernityqgltxmcgkykxsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVybml0eXFnbHR4bWNna3lreHN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzM2MzUsImV4cCI6MjA2OTIwOTYzNX0.nhzHytqxakNmVe33sz2g-Jj0SrIR5UQBmoN_p95xohc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});